name: Test Workflow File

on: 
  push:
    branches:
      - main
        
jobs:
  job1:
    name: API Call via action
    runs-on: ubuntu-latest
    outputs:
       matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - name: Checkout branch
        id: checkout_repo
        uses: actions/checkout@v3
        with:
          ref: main
     
      - name: List Repo Contents
        id: get_repo_contents
        run: |
            ls .
        
      # - name: Get JSON Data
      #   id: repository_type
      #   uses: zoexx/github-action-json-file-properties@release
      #   with:
      #     file_path: "destination.json"
      #     prop_path: "endpoint"

      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls ./*.json | jq -R -s -c 'split("\n")[:-1]')"

      - name: Display Endpoint to Call
        run: |
            echo ${{steps.repository_type.outputs.value}}

  job2:
    name: Call Endpoint(s)
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        endpoints: ${{needs.job1.outputs.matrix}}

    steps:
    - name: Call API
      id: apiCall
      uses: 'DeclanRodgers/get-and-print-github-action@v1.1'
      with:
        api-endpoint-url: ${{ matrix.endpoints }}
